version: "1.0"
services:
  backend:
    build: ./Backend/
    image: bicas-backend
    container_name: bicas-backend
    restart: always
    network_mode: "host"
    # ports:
    #   - 8282:8282
    volumes:
      - ./logs/:/Backend/logs/
  nginx:
    build: ./nginx/
    image: bicas-nginx
    container_name: bicas-nginx
    restart: always
    network_mode: "host"
    volumes:
      - ./BicasCasino/src/public:/public
  db:
    image: postgres:14.1-alpine
    container_name: bicas-db
    restart: always
    environment:
      - POSTGRES_USER=bicas
      - POSTGRES_PASSWORD=bicas
      - APP_DB_USER=bicas
      - APP_DB_PASS=bicas
      - APP_DB_NAME=bicas
    # ports:
    #   - '5433:5433'
    network_mode: "host"
    volumes:
      - ./db-data/:/var/lib/postgresql/data
      - ./Backend/db_scheme/scheme.sql:/docker-entrypoint-initdb.d/create_tables.sql

# volumes:
#   db:
#     driver: local
